
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listJobs(query: JobQuery) : Promise<Result<JobSummary[], SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_jobs", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getJob(id: string) : Promise<Result<Job, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_job", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createJob(input: CreateJobInput) : Promise<Result<Job, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_job", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateJob(id: string, patch: UpdateJobInput) : Promise<Result<Job, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_job", { id, patch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async transitionJob(id: string, input: TransitionJobInput) : Promise<Result<Job, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transition_job", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteJob(id: string) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_job", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readJd(id: string) : Promise<Result<string, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_jd", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateJd(id: string, markdown: string) : Promise<Result<Job, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_jd", { id, markdown }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listJobEvents(id: string) : Promise<Result<JobEvent[], SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_job_events", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addCommunication(id: string, input: AddCommunicationInput) : Promise<Result<Communication, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_communication", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listCommunications(id: string) : Promise<Result<Communication[], SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_communications", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addApplication(id: string, input: AddApplicationInput) : Promise<Result<Application, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_application", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listApplications(id: string) : Promise<Result<Application[], SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_applications", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async upsertInterview(id: string, input: UpsertInterviewInput) : Promise<Result<InterviewRound, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_interview", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listInterviews(id: string) : Promise<Result<InterviewRound[], SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_interviews", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reorderInterview(id: string, interviewId: string, newSequence: number) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reorder_interview", { id, interviewId, newSequence }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dashboardMetrics() : Promise<Result<DashboardMetrics, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dashboard_metrics") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importMarkdown(path: string, normalizedMarkdown: string, title: string, templateId: string) : Promise<Result<Resume, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_markdown", { path, normalizedMarkdown, title, templateId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createBaseResume(title: string, markdown: string) : Promise<Result<Resume, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_base_resume", { title, markdown }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readResume(id: string) : Promise<Result<ResumeContent, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_resume", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveResume(input: SaveResumeInput) : Promise<Result<Resume, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_resume", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createResumeVersion(id: string, title: string) : Promise<Result<Resume, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_resume_version", { id, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async duplicateResume(id: string) : Promise<Result<Resume, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("duplicate_resume", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLayout(id: string) : Promise<Result<LayoutConfig | null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_layout", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveLayout(id: string, config: LayoutConfig) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_layout", { id, config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listResumes() : Promise<Result<Resume[], SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_resumes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteResume(id: string) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_resume", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 前端用 @jsw/template-engine 渲染出最终 HTML 后调用此命令导出 PDF。
 */
async exportPdfRendered(resumeId: string, templateId: string, renderedHtml: string, pageCss: string, outputPath: string) : Promise<Result<PdfExportResult, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_pdf_rendered", { resumeId, templateId, renderedHtml, pageCss, outputPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTemplates() : Promise<Result<Template[], SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_templates") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTemplateEnabled(id: string, enabled: boolean) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_template_enabled", { id, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importTemplateZip(zipPath: string) : Promise<Result<Template, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_template_zip", { zipPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readTemplateAssets(id: string) : Promise<Result<TemplateAssets, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_template_assets", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 生成模板静态预览图（spec §8.3）：前端渲染 mock HTML，Rust 用 WKWebView 快照为 PNG。
 */
async saveTemplatePreview(templateId: string, renderedHtml: string) : Promise<Result<string, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_template_preview", { templateId, renderedHtml }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 读取模板静态预览图（base64 data URL）；未生成时返回 null。
 */
async readTemplatePreview(templateId: string) : Promise<Result<string | null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_template_preview", { templateId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readAiStatus() : Promise<Result<AIServiceStatus, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_ai_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 读取 codex 路径覆盖（None = 自动发现）。
 */
async getCodexPathOverride() : Promise<Result<string | null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_codex_path_override") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 设置 codex 路径覆盖：空串清除（回到自动发现）；非空校验文件存在。
 */
async setCodexPathOverride(path: string) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_codex_path_override", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 启动 App Server 并完成 initialize 握手（spec §10.3）。
 */
async startAppServer() : Promise<Result<string, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_app_server") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startLogin(input: LoginInput) : Promise<Result<LoginStartResult, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_login", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async logout() : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("logout") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSkills(forceReload: boolean) : Promise<Result<SkillInfo[], SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_skills", { forceReload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSkillEnabled(path: string, enabled: boolean) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_skill_enabled", { path, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 从本地目录导入 Skill（复制进工作区 .agents/skills）。
 */
async importSkill(path: string, replace: boolean) : Promise<Result<string, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_skill", { path, replace }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除已导入的 Skill（内置拒绝）。
 */
async deleteSkill(name: string) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_skill", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async enqueueRun(input: EnqueueAIRunInput) : Promise<Result<AIRun, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("enqueue_run", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelRun(id: string) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_run", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRuns(jobId: string | null) : Promise<Result<AIRun[], SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_runs", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 读取某岗位正式的分析/调研产物（artifact 登记过的文件）。
 */
async readJobArtifacts(jobId: string) : Promise<Result<RunOutput[], SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_job_artifacts", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listArtifacts(jobId: string) : Promise<Result<Artifact[], SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_artifacts", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createBackup() : Promise<Result<string, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_backup") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restoreBackup(backupPath: string) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_backup", { backupPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async appInfo() : Promise<Result<AppInfoResult, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("app_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 导入预览：读取用户通过原生对话框选择的 Markdown 源文件内容。
 * UI 不直接访问文件系统，统一走此命令（spec §17）。
 */
async readImportSource(path: string) : Promise<Result<string, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_import_source", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runRecoveryScan() : Promise<Result<[number, number], SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_recovery_scan") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AIRun = { id: string; job_id: string | null; resume_id: string | null; run_type: string; status: string; thread_id: string | null; model: string | null; skill_snapshot_json: string; input_manifest_json: string; output_manifest_json: string | null; workdir_path: string; error_code: string | null; error_message: string | null; queued_at: string; started_at: string | null; finished_at: string | null }
export type AIRunType = "job_analysis" | "company_research" | "resume_tailoring"
export type AIServiceStatus = { codex_path: string | null; codex_version: string | null; app_server_state: string; logged_in: boolean | null; account_email: string | null; plan_type: string | null }
export type Actor = "user" | "system" | "ai"
export type AddApplicationInput = { applied_at: string; channel: string; notes: string }
export type AddCommunicationInput = { occurred_at: string; contact_name: string | null; channel: string; notes: string; advance_to_pending_application: boolean }
export type AppInfoResult = { version: string; app_data_dir: string }
export type Application = { id: string; job_id: string; applied_at: string; channel: string; notes: string; created_at: string }
export type Artifact = { id: string; job_id: string | null; resume_id: string | null; ai_run_id: string | null; kind: string; relative_path: string; sha256: string; metadata_json: string; created_at: string }
export type Communication = { id: string; job_id: string; occurred_at: string; contact_name: string | null; channel: string; notes: string; created_at: string }
export type CreateJobInput = { company_name: string; role_title: string; jd_markdown: string; source_url: string | null; location: string | null; salary_text: string | null }
export type DashboardMetrics = { total_active: number; pending: number; interviewing: number; passed: number; rejected: number }
export type EnqueueAIRunInput = { run_type: AIRunType; job_id: string; resume_id: string | null }
export type InterviewRound = { id: string; job_id: string; sequence: number; name: string; status: string; scheduled_at: string | null; format: string | null; interviewer: string | null; notes: string; result: string | null; created_at: string; updated_at: string }
export type Job = { id: string; company_name: string; role_title: string; status: JobStatus; 
/**
 * 相对 app_data_dir 的 POSIX 相对路径（spec §4.3），如 `workspace/jobs/<id>/jd.md`
 */
jd_path: string; source_url: string | null; location: string | null; salary_text: string | null; active_resume_id: string | null; terminal_reason: string | null; created_at: string; updated_at: string }
export type JobEvent = { id: string; job_id: string; event_type: string; from_status: JobStatus | null; to_status: JobStatus | null; actor: Actor; payload_json: string; occurred_at: string }
export type JobQuery = { status: JobStatus | null; search: string | null }
export type JobStatus = "pending_analysis" | "pending_resume_optimization" | "pending_communication" | "pending_application" | "interviewing" | "passed" | "rejected"
export type JobSummary = { id: string; company_name: string; role_title: string; status: JobStatus; location: string | null; salary_text: string | null; updated_at: string }
export type LayoutBlock = { id: string; 
/**
 * "section"（绑定 md 章节）| "text"（自由文案）| "heading"（纯标题组件）
 */
type: string; sectionId: string | null; 
/**
 * text 容器的 Markdown 内容
 */
markdown: string | null; 
/**
 * 12 栅格宽度：12 | 8 | 6 | 4
 */
width: number; hidden: boolean; 
/**
 * 卡片化（圆角浅底）
 */
card: boolean; 
/**
 * 浅色着色（rose/blue/indigo/…，None 为透明）
 */
tint: string | null; 
/**
 * 自定义标题：None 用章节原文；Some("") 隐藏标题；其他为替换文本
 */
titleOverride: string | null; 
/**
 * 字号档位："small" | "normal" | "large"（None 为 normal）
 */
size: string | null; 
/**
 * 与版式绑定："template"（默认，跟随版式风格）| "free"（通用组件，独立基础排版）
 */
binding: string | null; 
/**
 * 对齐："left" | "center" | "right"（free/heading/hero 组件生效）
 */
align: string | null; 
/**
 * 页头模式（隐藏章节标题、首行大字居中、首个列表横排）
 */
hero: boolean | null }
export type LayoutConfig = { page: PageSetup; blocks: LayoutBlock[]; theme: LayoutTheme }
export type LayoutTheme = { primary: string; 
/**
 * "sans" | "serif"
 */
font: string; 
/**
 * "compact" | "normal" | "airy"
 */
density: string; 
/**
 * 标题样式："bar"（现代简洁短条）| "dot"（时间线节点）| "plain"（无装饰）
 */
heading: string | null }
export type LoginInput = { mode: string; api_key?: string | null }
export type LoginStartResult = { kind: string; auth_url: string | null; verification_url: string | null; user_code: string | null }
export type PageSetup = { 
/**
 * 四边距（mm），容器区在剩余空间水平居中
 */
marginTop: number; marginRight: number; marginBottom: number; marginLeft: number; headerEnabled: boolean; headerHeightMm: number; 
/**
 * 页眉文案（Markdown，单行段落即可）
 */
headerMarkdown: string | null; footerEnabled: boolean; footerHeightMm: number; footerPageNumbers: boolean; footerMarkdown: string | null }
export type PdfExportResult = { output_path: string; page_count: number; sha256: string }
export type Resume = { id: string; title: string; kind: ResumeKind; markdown_path: string; parent_resume_id: string | null; job_id: string | null; template_id: string; content_sha256: string; created_at: string; updated_at: string }
export type ResumeContent = { resume: Resume; markdown: string }
export type ResumeKind = "base" | "tailored"
export type RunOutput = { name: string; content: string }
export type SaveResumeInput = { id: string; title: string | null; markdown: string; template_id: string | null }
/**
 * 跨 IPC 的错误载体（Specta 可导出）。
 */
export type SerializedError = { code: string; message: string }
export type SkillInfo = { name: string; description: string; path: string | null; enabled: boolean; error: string | null; 
/**
 * 发现来源目录（工作区 / 本机个人目录等），UI 据此分组
 */
cwd: string }
export type Template = { id: string; name: string; origin: string; version: string; manifest_path: string; preview_path: string | null; enabled: boolean; created_at: string; updated_at: string }
export type TemplateAssets = { template_html: string; style_css: string; manifest_json: string }
export type TransitionJobInput = { to_status: JobStatus; reason: string | null }
export type UpdateJobInput = { company_name: string | null; role_title: string | null; source_url: string | null; location: string | null; salary_text: string | null }
export type UpsertInterviewInput = { id: string | null; sequence: number | null; name: string; status: string; scheduled_at: string | null; format: string | null; interviewer: string | null; notes: string; result: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
