/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as ResumesIndexRouteImport } from './routes/resumes.index'
import { Route as TemplatesTemplateIdRouteImport } from './routes/templates.$templateId'
import { Route as ResumesResumeIdEditRouteImport } from './routes/resumes.$resumeId.edit'
import { Route as ResumesResumeIdLayoutRouteImport } from './routes/resumes.$resumeId.layout'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesIndexRoute = ResumesIndexRouteImport.update({
  id: '/resumes/',
  path: '/resumes/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTemplateIdRoute = TemplatesTemplateIdRouteImport.update({
  id: '/$templateId',
  path: '/$templateId',
  getParentRoute: () => TemplatesRoute,
} as any)
const ResumesResumeIdEditRoute = ResumesResumeIdEditRouteImport.update({
  id: '/resumes/$resumeId/edit',
  path: '/resumes/$resumeId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesResumeIdLayoutRoute = ResumesResumeIdLayoutRouteImport.update({
  id: '/resumes/$resumeId/layout',
  path: '/resumes/$resumeId/layout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/resumes/': typeof ResumesIndexRoute
  '/resumes/$resumeId/edit': typeof ResumesResumeIdEditRoute
  '/resumes/$resumeId/layout': typeof ResumesResumeIdLayoutRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/jobs': typeof JobsIndexRoute
  '/resumes': typeof ResumesIndexRoute
  '/resumes/$resumeId/edit': typeof ResumesResumeIdEditRoute
  '/resumes/$resumeId/layout': typeof ResumesResumeIdLayoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/resumes/': typeof ResumesIndexRoute
  '/resumes/$resumeId/edit': typeof ResumesResumeIdEditRoute
  '/resumes/$resumeId/layout': typeof ResumesResumeIdLayoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/settings'
    | '/templates'
    | '/jobs/$jobId'
    | '/templates/$templateId'
    | '/jobs/'
    | '/resumes/'
    | '/resumes/$resumeId/edit'
    | '/resumes/$resumeId/layout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/settings'
    | '/templates'
    | '/jobs/$jobId'
    | '/templates/$templateId'
    | '/jobs'
    | '/resumes'
    | '/resumes/$resumeId/edit'
    | '/resumes/$resumeId/layout'
  id:
    | '__root__'
    | '/dashboard'
    | '/settings'
    | '/templates'
    | '/jobs/$jobId'
    | '/templates/$templateId'
    | '/jobs/'
    | '/resumes/'
    | '/resumes/$resumeId/edit'
    | '/resumes/$resumeId/layout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
  JobsJobIdRoute: typeof JobsJobIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ResumesIndexRoute: typeof ResumesIndexRoute
  ResumesResumeIdEditRoute: typeof ResumesResumeIdEditRoute
  ResumesResumeIdLayoutRoute: typeof ResumesResumeIdLayoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/': {
      id: '/resumes/'
      path: '/resumes'
      fullPath: '/resumes/'
      preLoaderRoute: typeof ResumesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$templateId': {
      id: '/templates/$templateId'
      path: '/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/resumes/$resumeId/edit': {
      id: '/resumes/$resumeId/edit'
      path: '/resumes/$resumeId/edit'
      fullPath: '/resumes/$resumeId/edit'
      preLoaderRoute: typeof ResumesResumeIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/$resumeId/layout': {
      id: '/resumes/$resumeId/layout'
      path: '/resumes/$resumeId/layout'
      fullPath: '/resumes/$resumeId/layout'
      preLoaderRoute: typeof ResumesResumeIdLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TemplatesRouteChildren {
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesTemplateIdRoute: TemplatesTemplateIdRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
  JobsJobIdRoute: JobsJobIdRoute,
  JobsIndexRoute: JobsIndexRoute,
  ResumesIndexRoute: ResumesIndexRoute,
  ResumesResumeIdEditRoute: ResumesResumeIdEditRoute,
  ResumesResumeIdLayoutRoute: ResumesResumeIdLayoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
